spring.application.name=video-slicer
# Configuração de upload de arquivos
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Configurações AWS
aws.region=us-east-1
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}

# Configurações S3
aws.s3.bucket-name=my-video-bucket
aws.s3.folder-prefix=videos/

# Configurações SQS
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/123456789012/video-processing-queue
