spring.application.name=video-slicer
# Configuração de upload de arquivos
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Configurações AWS
aws.region=us-east-1
aws.accessKeyId=730335547240
aws.secretAccessKey=/8l53GwnVwcQNnR07EuhFcliBPV3D7C1x+rOX/7J

# Configurações S3
aws.s3.bucket-name=fiap-hackatoon-videos
aws.s3.folder-prefix=videos/

# Configurações SQS
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/730335547240/video-processor
